version: '3.9'

services:
  search_engine_mysql:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: (&sDbWY^A4tz+wWj
      MYSQL_DATABASE: products
      MYSQL_USER: main
      MYSQL_PASSWORD: secretfoo
    ports:
      - 3308:3306
    volumes:
      - ./volumes/search_schemas:/var/lib/mysql
  

  action_mysql:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: (&sDbWY^A4tz+wWj
      MYSQL_DATABASE: actions
      MYSQL_USER: main
      MYSQL_PASSWORD: secretfoo
    ports:
      - 3307:3306
    volumes:
      - ./volumes/action_schemas:/var/lib/mysql